name: Build & Push Docker Image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_GITHUB }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: "ghcr.io/princekumar1291/github-action-java:latest"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image URL
      run: echo "Image pushed to ghcr.io/${{ github.repository }}:latest"